DROP TABLE IF EXISTS PRODUCTS_TBL;

CREATE TABLE PRODUCTS_TBL (
  id INT PRIMARY KEY NOT NULL,
  product_name VARCHAR(250) NOT NULL,
  product_value VARCHAR(250) NOT NULL,
  category VARCHAR(250) DEFAULT NULL
);

